services:
  web:
    build:
      context: "."
      dockerfile: ./Dockerfile
      target: "app"
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
        - "NODE_ENV=${NODE_ENV:-production}"
        - "FLASK_ENV=${FLASK_ENV:-production}"
    env_file:
      - ".env"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    tty: true
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:8000/api/up}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "${DOCKER_WEB_PORT_FORWARD:-8000}:${PORT:-8000}"
    profiles: ["web"]
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      # Linux configuration
      # - ${SSH_AUTH_SOCK}:/ssh-agent
      # MacOS configuration
      - /run/host-services/ssh-auth.sock:/ssh-agent

  # To connect to the container in the remote connection dialog use `ssh` and port `22`
  ssh:
    build:
      dockerfile: Dockerfile
      context: ./docker/SSH
      args:
        - "username=w0269804"
        # See README for SSH container for keypath
        - "keypath=./id_ed25519.pub"
    ports:
      - "${DOCKER_SSH_PORT_FORWARD:-2222}:22"
