[project]
name = "ttnn_visualizer"
version = "0.0.1"
authors = []
description = "TT Visualizer"
readme = "README.md"
requires-python = ">=3.12"
dependencies= [
"flask",
"gunicorn~=22.0.0",
"uvicorn==0.30.1",
"paramiko~=3.4.0",
"marshmallow==3.21.3",
"flask_marshmallow==1.2.1",
"flask_cors==4.0.1",
"flask_sqlalchemy==3.1.1",
"pydantic==2.7.3",
"pydantic_core==2.18.4",
"flask_static_digest==0.4.1",
"marshmallow-sqlalchemy==1.0.0",
"setuptools==65.5.0",
"python-dotenv==1.0.1",

]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[tool.setuptools]
package-dir = {"" = "backend"}

[tool.setuptools.packages.find]
where = ["backend"]


[build-system]
requires = [
  "setuptools==69.5.1",
  "setuptools-scm==7.1.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project.scripts]
ttnn-visualizer = "ttnn_visualizer.appserver:serve"
