[project]
name = "ttnn_visualizer"
authors = []
version = "0.12.0"
description = "TT Visualizer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "gunicorn~=22.0.0",
    "paramiko~=3.4.0",
    "flask_cors==4.0.1",
    "pydantic==2.7.3",
    "pydantic_core==2.18.4",
    "flask_static_digest==0.4.1",
    "setuptools==65.5.0",
    "gevent===24.10.1",
    "python-dotenv==1.0.1",
    "sqlalchemy==2.0.34",
    "flask-socketio==5.4.1",
    "flask-sqlalchemy==3.1.1"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[tool.setuptools]
package-dir = { "" = "backend" }

[tool.setuptools.packages.find]
where = ["backend"]

[build-system]
requires = ["setuptools==69.5.1", "setuptools-scm==7.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
ttnn-visualizer = "ttnn_visualizer.app:main"

[tool.black]
line-length = 88
target-version = ['py37']
include = 'backend/\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist

    # The following are specific to Black, you probably don't want those.
    | blib2to3
    | tests/data
)/
'''

