# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 127.0.0.1:9090:9090
    restart: unless-stopped
    volumes:
      - ${PROMETHEUS_CONFIG_FILE:-./prometheus.generated.yml}:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

volumes:
  prometheus-data:
