name: Lint and Test

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint and Test (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      -   name: Read .nvmrc
          id: nvm
          run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      -   name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
              cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get changed files in PR
        id: pr_changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }})
          echo "changed=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Print changed files
        run: |
          echo "Changed files: ${{ steps.pr_changes.outputs.changed }}"

      - name: Lint and test
        run: |
          pnpm lint
          pnpm test

  backend-lint-and-test:
    name: Lint and Test (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.16'

      - name: Install dependencies
        run: pip install .[dev]

      - name: Run Black
        run: black --check backend/ttnn_visualizer

      - name: Run Backend Tests
        run: pytest backend/ttnn_visualizer
