name: Lint and Test Workflow

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint and Test (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      -   name: Read .nvmrc
          id: nvm
          run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      -   name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm install -g pnpm@latest-10
          pnpm install

      - name: Lint and test
        run: |
          pnpm lint
          pnpm test
  backend-lint-and-test:
    name: Lint and Test (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.16'

      - name: Install dependencies
        run: pip install .[dev]

      - name: Run Black
        run: black --check backend/ttnn_visualizer

      - name: Run Backend Tests
        run: pytest backend/ttnn_visualizer
