name: Lint and Test Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
    update-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: actions/setup-node@v4
              with:
                node-version: v20.11.1
            - run: npm install -g pnpm@latest-10
            - run: pnpm install

            - name: Lint and test
              run: |
                pnpm run lint
                pnpm run test
