name: Lint and Test Workflow

on:
  pull_request:
    branches: [ "dev" ]

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: actions/setup-node@v4
              with:
                node-version: v20.11.1
            - run: npm install -g pnpm@latest-10
            - run: pnpm install
            - run: pnpm run lint
            - run: pnpm run test
